[package]
name = "rstris_demo"
version = "0.1.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
edition = "2018"

[dependencies]
sdl2 = "*"
time = "0.1"
rand = "*"
log = "0.4.6"
fern = "0.5.8"
chrono = "0.4.6"

[dependencies.rstris]
path = "rstris"
